//! Configuration loading and validation.
//!
//! Parses the TOML config file generated by `install.sh` into typed structs.
//! Validates all regex patterns at load time to fail fast.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

/// Top-level configuration.
#[derive(Debug, Deserialize)]
pub struct Config {
    #[serde(default)]
    pub gateway: GatewayConfig,
    #[serde(default)]
    pub security: SecurityConfig,
    #[serde(default)]
    pub channels: ChannelsConfig,
}

/// Gateway network / runtime settings.
#[derive(Debug, Deserialize)]
pub struct GatewayConfig {
    #[serde(default = "default_socket_path")]
    pub socket_path: PathBuf,
    #[serde(default = "default_log_level")]
    pub log_level: String,
    #[serde(default = "default_request_timeout")]
    pub request_timeout: u64,
}

impl Default for GatewayConfig {
    fn default() -> Self {
        Self {
            socket_path: PathBuf::from(default_socket_path()),
            log_level: default_log_level(),
            request_timeout: default_request_timeout(),
        }
    }
}

/// Channel configuration — each field is an optional channel.
#[derive(Debug, Default, Deserialize)]
pub struct ChannelsConfig {
    pub imsg: Option<ImsgChannelConfig>,
    pub gmail: Option<GmailChannelConfig>,
}

/// Configuration for the Gmail channel.
///
/// Supports two formats:
/// - **Legacy single-account:** `proxy_socket` field (backward-compatible)
/// - **Multi-account:** `accounts` table with named accounts
///
/// When the legacy format is used, the daemon treats it as a single account
/// named "default". Old configs and MCP clients that don't pass an `account`
/// parameter continue to work unchanged.
#[derive(Debug, Deserialize)]
pub struct GmailChannelConfig {
    #[serde(default = "default_true")]
    pub enabled: bool,

    /// Legacy single-account field. If `accounts` is also present, this is ignored.
    #[serde(default)]
    pub proxy_socket: Option<PathBuf>,

    /// Named accounts, each with its own proxy socket and inbound config.
    #[serde(default)]
    pub accounts: Option<HashMap<String, GmailAccountConfig>>,

    /// Which account to use when no `account` param is specified in a request.
    /// Defaults to "default" (legacy) or the first account in the map.
    pub default_account: Option<String>,

    /// Legacy inbound config (used when `proxy_socket` is set without `accounts`).
    #[serde(default)]
    pub inbound: DirectionConfig,
}

/// Configuration for a single Gmail account within the multi-account setup.
#[derive(Debug, Clone, Deserialize)]
pub struct GmailAccountConfig {
    pub proxy_socket: PathBuf,
    #[serde(default)]
    pub inbound: DirectionConfig,
}

impl GmailChannelConfig {
    /// Resolve to a map of account_name → GmailAccountConfig.
    ///
    /// Handles both legacy (single `proxy_socket`) and new (`accounts` map) formats.
    pub fn resolve_accounts(&self) -> HashMap<String, GmailAccountConfig> {
        if let Some(ref accounts) = self.accounts {
            accounts.clone()
        } else if let Some(ref socket) = self.proxy_socket {
            let mut map = HashMap::new();
            map.insert(
                "default".to_string(),
                GmailAccountConfig {
                    proxy_socket: socket.clone(),
                    inbound: self.inbound.clone(),
                },
            );
            map
        } else {
            // No proxy_socket and no accounts — use the default socket path.
            let mut map = HashMap::new();
            map.insert(
                "default".to_string(),
                GmailAccountConfig {
                    proxy_socket: default_gmail_socket(),
                    inbound: self.inbound.clone(),
                },
            );
            map
        }
    }

    /// Get the default account name for requests that don't specify one.
    pub fn default_account_name(&self) -> &str {
        self.default_account.as_deref().unwrap_or("default")
    }
}

fn default_gmail_socket() -> PathBuf {
    PathBuf::from("/var/run/carapace/gmail-proxy.sock")
}

/// Configuration for the iMessage channel.
#[derive(Debug, Deserialize)]
pub struct ImsgChannelConfig {
    #[serde(default = "default_true")]
    pub enabled: bool,
    #[serde(default = "default_imsg_binary")]
    pub real_binary: PathBuf,
    #[serde(default = "default_imsg_db")]
    pub db_path: PathBuf,
    #[serde(default)]
    pub outbound: DirectionConfig,
    #[serde(default)]
    pub inbound: DirectionConfig,
}

/// Per-direction allowlist/denylist configuration.
#[derive(Debug, Clone, Deserialize)]
pub struct DirectionConfig {
    #[serde(default)]
    pub mode: AllowlistMode,
    #[serde(default)]
    pub allowlist: Vec<String>,
}

impl Default for DirectionConfig {
    fn default() -> Self {
        Self {
            mode: AllowlistMode::default(),
            allowlist: Vec::new(),
        }
    }
}

/// How the allowlist is interpreted.
#[derive(Debug, Default, Clone, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AllowlistMode {
    /// Only identifiers in the list are allowed.
    #[default]
    Allowlist,
    /// All identifiers are allowed except those in the list.
    Denylist,
    /// All identifiers are allowed (no filtering).
    Open,
}

fn default_imsg_binary() -> PathBuf {
    PathBuf::from("/Users/carapace/.local/bin/imsg")
}

fn default_imsg_db() -> PathBuf {
    PathBuf::from("/Users/carapace/Library/Messages/chat.db")
}

fn default_socket_path() -> PathBuf {
    PathBuf::from("/var/run/carapace/gateway.sock")
}
fn default_log_level() -> String {
    "info".into()
}
fn default_request_timeout() -> u64 {
    30
}

/// Security settings: audit, rate limiting, content filtering.
#[derive(Debug, Deserialize)]
pub struct SecurityConfig {
    #[serde(default = "default_audit_log_path")]
    pub audit_log_path: PathBuf,
    #[serde(default = "default_dead_letter_path")]
    pub dead_letter_path: PathBuf,
    #[serde(default = "default_true")]
    pub audit_enabled: bool,
    #[serde(default)]
    pub rate_limit: RateLimitConfig,
    #[serde(default)]
    pub content_filter: ContentFilterConfig,
}

impl Default for SecurityConfig {
    fn default() -> Self {
        Self {
            audit_log_path: default_audit_log_path(),
            dead_letter_path: default_dead_letter_path(),
            audit_enabled: true,
            rate_limit: RateLimitConfig::default(),
            content_filter: ContentFilterConfig::default(),
        }
    }
}

fn default_audit_log_path() -> PathBuf {
    PathBuf::from("/Users/carapace/.local/share/carapace/audit.log")
}
fn default_dead_letter_path() -> PathBuf {
    PathBuf::from("/Users/carapace/.local/share/carapace/dead_letters")
}
fn default_true() -> bool {
    true
}

/// Per-channel rate limits. Keys are channel names or "default".
#[derive(Debug, Default, Clone, Deserialize)]
#[serde(transparent)]
pub struct RateLimitConfig {
    pub entries: HashMap<String, RateLimitEntry>,
}

/// A single rate-limit rule.
#[derive(Debug, Clone, Deserialize)]
pub struct RateLimitEntry {
    pub requests: u32,
    pub per_seconds: u64,
}

/// Content filtering configuration.
#[derive(Debug, Deserialize)]
pub struct ContentFilterConfig {
    #[serde(default = "default_true")]
    pub enabled: bool,
    #[serde(default)]
    pub patterns: Vec<PatternEntry>,
}

impl Default for ContentFilterConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            patterns: Vec::new(),
        }
    }
}

/// A single content-filter pattern.
#[derive(Debug, Deserialize)]
pub struct PatternEntry {
    pub pattern: String,
    #[serde(default)]
    pub action: FilterAction,
}

/// What to do when a pattern matches.
#[derive(Debug, Default, Clone, PartialEq, Eq, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum FilterAction {
    #[default]
    Block,
    Warn,
}

/// Errors that can occur when loading configuration.
#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("failed to read config file: {0}")]
    Io(#[from] std::io::Error),
    #[error("failed to parse config TOML: {0}")]
    Parse(#[from] toml::de::Error),
    #[error("invalid regex in content_filter pattern {index}: {source}")]
    BadRegex {
        index: usize,
        source: regex::Error,
    },
}

impl Config {
    /// Load configuration from a TOML file.
    ///
    /// All regex patterns are compiled to validate them; the compiled forms
    /// are used later by [`ContentFilter`](crate::content_filter::ContentFilter).
    pub fn load(path: &Path) -> Result<Self, ConfigError> {
        let text = std::fs::read_to_string(path)?;
        let config: Config = toml::from_str(&text)?;
        config.validate()?;
        Ok(config)
    }

    /// Built-in defaults for when no config file exists (e.g. `--quick-test`).
    pub fn defaults() -> Self {
        Config {
            gateway: GatewayConfig::default(),
            security: SecurityConfig::default(),
            channels: ChannelsConfig::default(),
        }
    }

    /// Validate all regex patterns compile successfully.
    fn validate(&self) -> Result<(), ConfigError> {
        for (i, entry) in self.security.content_filter.patterns.iter().enumerate() {
            regex::Regex::new(&entry.pattern).map_err(|e| ConfigError::BadRegex {
                index: i,
                source: e,
            })?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_minimal_config() {
        let toml_str = r#"
[gateway]
socket_path = "/tmp/test.sock"
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        config.validate().unwrap();
        assert_eq!(
            config.gateway.socket_path,
            PathBuf::from("/tmp/test.sock")
        );
        assert_eq!(config.gateway.log_level, "info");
        assert_eq!(config.gateway.request_timeout, 30);
        assert!(config.security.audit_enabled);
    }

    #[test]
    fn parse_full_config_with_patterns() {
        let toml_str = r#"
[gateway]
socket_path = "/var/run/carapace/gateway.sock"
log_level = "debug"
request_timeout = 15

[security]
audit_log_path = "/tmp/audit.log"
dead_letter_path = "/tmp/dead_letters"
audit_enabled = true

[security.rate_limit]
default = { requests = 30, per_seconds = 60 }
imsg    = { requests = 10, per_seconds = 30 }

[security.content_filter]
enabled = true

[[security.content_filter.patterns]]
pattern = '(?i)password\s*[:=]'
action  = "block"

[[security.content_filter.patterns]]
pattern = '\b\d{3}-\d{2}-\d{4}\b'
action  = "warn"
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        config.validate().unwrap();
        assert_eq!(config.gateway.log_level, "debug");
        assert_eq!(config.gateway.request_timeout, 15);
        assert_eq!(config.security.content_filter.patterns.len(), 2);
        assert_eq!(
            config.security.content_filter.patterns[0].action,
            FilterAction::Block
        );
        assert_eq!(
            config.security.content_filter.patterns[1].action,
            FilterAction::Warn
        );

        let default_limit = config.security.rate_limit.entries.get("default").unwrap();
        assert_eq!(default_limit.requests, 30);
        assert_eq!(default_limit.per_seconds, 60);

        let imsg_limit = config.security.rate_limit.entries.get("imsg").unwrap();
        assert_eq!(imsg_limit.requests, 10);
    }

    #[test]
    fn reject_invalid_regex() {
        let toml_str = r#"
[security.content_filter]
enabled = true

[[security.content_filter.patterns]]
pattern = '[invalid'
action  = "block"
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        let err = config.validate().unwrap_err();
        assert!(matches!(err, ConfigError::BadRegex { index: 0, .. }));
    }

    #[test]
    fn defaults_are_valid() {
        let config = Config::defaults();
        config.validate().unwrap();
        assert!(config.security.audit_enabled);
        assert!(config.security.content_filter.patterns.is_empty());
        assert!(config.channels.imsg.is_none());
    }

    #[test]
    fn parse_channel_config_with_allowlist() {
        let toml_str = r#"
[channels.imsg]
enabled = true
real_binary = "/usr/local/bin/imsg"
db_path = "/Users/carapace/Library/Messages/chat.db"

[channels.imsg.outbound]
mode = "allowlist"
allowlist = ["+1234567890", "friend@icloud.com"]

[channels.imsg.inbound]
mode = "open"
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        let imsg = config.channels.imsg.unwrap();
        assert!(imsg.enabled);
        assert_eq!(imsg.real_binary, PathBuf::from("/usr/local/bin/imsg"));
        assert_eq!(imsg.outbound.mode, AllowlistMode::Allowlist);
        assert_eq!(imsg.outbound.allowlist.len(), 2);
        assert_eq!(imsg.outbound.allowlist[0], "+1234567890");
        assert_eq!(imsg.inbound.mode, AllowlistMode::Open);
        assert!(imsg.inbound.allowlist.is_empty());
    }

    #[test]
    fn parse_channel_config_denylist() {
        let toml_str = r#"
[channels.imsg]
enabled = true

[channels.imsg.outbound]
mode = "denylist"
allowlist = ["blocked@example.com"]
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        let imsg = config.channels.imsg.unwrap();
        assert_eq!(imsg.outbound.mode, AllowlistMode::Denylist);
        assert_eq!(imsg.outbound.allowlist.len(), 1);
    }

    #[test]
    fn parse_gmail_channel_config() {
        let toml_str = r#"
[channels.gmail]
enabled = true
proxy_socket = "/var/run/carapace/gmail-proxy.sock"

[channels.gmail.inbound]
mode = "open"
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        let gmail = config.channels.gmail.unwrap();
        assert!(gmail.enabled);
        assert_eq!(
            gmail.proxy_socket,
            Some(PathBuf::from("/var/run/carapace/gmail-proxy.sock"))
        );
        assert_eq!(gmail.inbound.mode, AllowlistMode::Open);

        // Legacy format should resolve to one "default" account.
        let accounts = gmail.resolve_accounts();
        assert_eq!(accounts.len(), 1);
        assert!(accounts.contains_key("default"));
        assert_eq!(
            accounts["default"].proxy_socket,
            PathBuf::from("/var/run/carapace/gmail-proxy.sock")
        );
    }

    #[test]
    fn parse_gmail_multi_account_config() {
        let toml_str = r#"
[channels.gmail]
enabled = true
default_account = "primary"

[channels.gmail.accounts.primary]
proxy_socket = "/var/run/carapace/gmail-proxy-primary.sock"

[channels.gmail.accounts.primary.inbound]
mode = "open"

[channels.gmail.accounts.wedding]
proxy_socket = "/var/run/carapace/gmail-proxy-wedding.sock"

[channels.gmail.accounts.wedding.inbound]
mode = "allowlist"
allowlist = ["vendor@example.com"]
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        let gmail = config.channels.gmail.unwrap();
        assert!(gmail.enabled);
        assert_eq!(gmail.default_account_name(), "primary");

        let accounts = gmail.resolve_accounts();
        assert_eq!(accounts.len(), 2);
        assert_eq!(
            accounts["primary"].proxy_socket,
            PathBuf::from("/var/run/carapace/gmail-proxy-primary.sock")
        );
        assert_eq!(accounts["primary"].inbound.mode, AllowlistMode::Open);
        assert_eq!(
            accounts["wedding"].proxy_socket,
            PathBuf::from("/var/run/carapace/gmail-proxy-wedding.sock")
        );
        assert_eq!(accounts["wedding"].inbound.mode, AllowlistMode::Allowlist);
        assert_eq!(accounts["wedding"].inbound.allowlist.len(), 1);
    }

    #[test]
    fn missing_channels_section_uses_defaults() {
        let toml_str = r#"
[gateway]
socket_path = "/tmp/test.sock"
"#;
        let config: Config = toml::from_str(toml_str).unwrap();
        assert!(config.channels.imsg.is_none());
    }
}
